version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '04:00'
    groups:
      npm-major:
        patterns:
          - '*'
        update-types:
          - 'major'
      npm-minor-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '@testing-library/jest-dom'
      - dependency-name: '@testing-library/react'
      - dependency-name: 'vitest'
      - dependency-name: 'zod'
    open-pull-requests-limit: 5
